spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mosBackEnd?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl_auto: update

    show-sql: true